name: IridiumChunkBusters
version: 1.0.0
description: A  plugin for removing chunks
main: com.iridium.chunkbusters.IridiumChunkBusters
api-version: '1.13'
author: Peaches_MLG
softdepend:
  - FactionsX
  - Factions
commands:
  chunkbusters:
    aliases: [ "cb" ]
    description: Main plugin command